### ISSUE TITLE
Example signature in Readme isn't parsed properly

### ISSUE THREAD

**Issue by wasabigeek** [mailgun/talon#110]
Using Python 3.4.3 + Talon without ML:

```
from talon.signature.bruteforce import extract_signature

text, signature = extract_signature("""Wow. Awesome!
    --
    Bob Smith"""
)
```

signature gives `None`.

@umairwaheed maybe you've already resolved this?

**Comment by obukhov-sergey** [comment]
Sorry @wasabigeek, couldn't reproduce the issue. Maybe it was already fixed or maybe it's Python 3 specific - I was testing on Python 2.7. The lib might be not fully Python 3 compatible yet.

**Comment by MinasAbrahamyan** [comment]
Just say talon is not for Python 3, not then, not now. (Not that I miss it, but let's be honest, you didn't try to reproduce it in mentioned conditions at all, i.e. with Python 3)
