### ISSUE TITLE
Forwarded message from GMail does not behave the same as Replied message

### ISSUE THREAD

**Issue by conapart3** [mailgun/talon#116]
--- Forwarded message --- is prepended to an email which is being forwarded by the Gmail client.

--- Original message --- is prepended to emails which are being replied to. In this case, Talon splits "--- Original message ---" into its own email. 

The behavior should be the same for Forwarded message so that these prefixes can be dealt with in the same way. Currently, --- Forwarded message --- is just appended to the end of the forwarding email.

**Comment by obukhov-sergey** [comment]
This is by design: when you reply to a message you, generally, put some reply, when you forward a message, the "reply" part is usually empty i.e. the value is solely in the forwarded message, so there is no point in stripping it out.

**Comment by MinasAbrahamyan** [comment]
Sure, you should strip it off, all the forwarded text, that's just logical; Forwarded message sometimes contain author text, and we use talon to get sithor text, so we should get eventually cleaned up text ; if that author text is absent, the resulting string will be empty, no problem with that, that was honest and correct. If we don't want to clean the text up, we will not call talon from the very start.
