### ISSUE TITLE
Stripping text that is part of the reply

### ISSUE THREAD

**Issue by chrismhilton** [mailgun/talon#129]
Whilst using mailgun routes to forward emails into our application we've had a few occasions where the stripped-text parameter is excluding information that is not a quoted part or signature block. The mailgun support team have recommended submitting an issue here so below I've listed a couple of examples for which the common denominator appears to be the presence of a colon (:) in the body text.

**Example 1**

body-plain

> "Hi Keith,\r\n\r\nI don't know how they were not sent. I did\r\n\r\nsomething wrong, sorry. Here they are:-\r\n\r\nVisa\r\n\r\nDiane K Littlechurch\r\n\r\n4011 3000 1333 7555\r\n\r\n06/17\r\n\r\nHope all is locked in now.\r\n\r\nMany thanks Keith\r\n\r\nCheers Kaye"

stripped-text

> "Hi Keith,\r\n\r\nI don't know how they were not sent. I did\r\n\r\nsomething wrong, sorry. Here they are:-\r\n\r\nVisa\r\n"

**Example 2**

body-plain

> "Also, have you billed and been paid for any of the weekly package =\r\nequipment?\r\n\r\nTry adding these emails to your Vision Team contacts:\r\n\r\nlampa@vision.hu <mailto:lampa@vision.hu>\r\n\r\ngabor@vision.hu <mailto:gabor@vision.hu>\r\n\r\noffice@vision.hu <mailto:office@vision.hu>\r\n\r\n\r\nWalter White\r\n+36 30 333 4151\r\n818-333-7089\r\nwalterwhite@gmail.com"

stripped-text

> "Also, have you billed and been paid for any of the weekly package =\r\nequipment?\r\n\r\nTry adding these emails to your Vision Team contacts:\r\n"

**Comment by obukhov-sergey** [comment]
Hi @chrismhilton, the excluded information looks exactly like email signature would. I'm not saying that it is, just that it's next to impossible to classify such cases properly. It's fairly easy for me and you i.e. humans, cause we understand what the written sentences mean. The machine doesn't, so it looks for lines length, if an email address is present there, etc. If in doubt you can always concatenate "stripped-text" and "stripped-signature". Unfortunately there is nothing else I can offer.

**Comment by colllin** [comment]
I've seen more obvious cases than this.

```
Great! Can you come in for a free trial tomorrow at 2PM?

Or what day/time works best for you?

John Smith
```

gets parsed as just... `Great! Can you come in for a free trial tomorrow at 2PM?`.

**Comment by ChiragMoradiya** [comment]
We also encountered the same issue in https://kerika.com

Our users are allowed to reply to any chat message through email. Kerika Server receives this email through Maligun's Webhook, and uses `stripped-text` value to post the message on behalf of the user.

See, Attached Screensot & Webhook Response JSON for reference.

![replay-via-emai-text-_cfa_W8My5X1REHwys5PHXcXxS_](https://github.com/mailgun/talon/assets/2399621/c91d739f-9eb2-461a-99b2-2e2d4ac3b1db)
[reply-via-email-response-(cfa_1lCsls7GhwJZm5af0YnS7e).log](https://github.com/mailgun/talon/files/13758076/reply-via-email-response-.cfa_1lCsls7GhwJZm5af0YnS7e.log)
