### ISSUE TITLE
Quotations parser gets stuck

### ISSUE THREAD

**Issue by Nipsuli** [mailgun/talon#168]
I had a an email where `mark_message_lines` produces following markers:
```
'tetetesssssmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmeetttttttttteteetttttttttteeetttttteeettttteeetttttttttteeettttt'
```

that gets completely stuck in `re.finditer('(?<=m)e*((?:t+e*)+)m', markers)` on line 289 in quotations.py

Basically the regex causes [Catastrophic Backtracking](https://www.regular-expressions.info/catastrophic.html)

talon 1.4.4
Python 3.6.5
[GCC 6.3.0 20170516] on linux

**Comment by ad-m** [comment]
I think it should be rewritten as ```(?<=m)e*(t[te]+)m```. What do you think, @Nipsuli ? 

```python-console
>>> re.search('(?<=m)e*((?:t+e*)+)m', 'metetetetetetetem').groups()
('tetetetetetete',)
>>> re.search('(?<=m)e*(t[te]+)m', 'metetetetetetetem').groups()
('tetetetetetete',)
```

That issues hit me also. Few times in last week.

**Comment by Nipsuli** [comment]
Seems to be in the correct direction. I think the quantifier should be `*` instead of `+` so `(?<=m)e*(t[te]*)m`

```
>>> re.search('(?<=m)e*((?:t+e*)+)m', 'metetetetetetetem').groups()
('tetetetetetete',)
>>> re.search('(?<=m)e*(t[te]+)m', 'metetetetetetetem').groups()
('tetetetetetete',)
>>> re.search('(?<=m)e*(t[te]*)m', 'metetetetetetetem').groups()
('tetetetetetete',)
>>>
>>> re.search('(?<=m)e*((?:t+e*)+)m', 'mtm').groups()
('t',)
>>> re.search('(?<=m)e*(t[te]+)m', 'mtm').groups()  # AttributeError: 'NoneType' object has no attribute 'groups'
>>> re.search('(?<=m)e*(t[te]*)m', 'mtm').groups()
('t',)
```

**Comment by ad-m** [comment]
@Nipsuli , I created a new pull requests as #172 to push forward that issue.

**Comment by obukhov-sergey** [comment]
@ad-m fixed with https://github.com/mailgun/talon/pull/172, thx for the PR!
