### ISSUE TITLE
Training Talon with our email set

### ISSUE THREAD

**Issue by qxh5696** [mailgun/talon#173]
Hey Mailgun Team,

How can I go about using our collection of emails to better train talon? 

More specifically, what steps do I have to do to put our emails in format that can be fed into the training data.

I was reading [this comment](https://github.com/mailgun/talon/issues/72#issuecomment-167884680) on an earlier issue and saw the following python file: 

https://github.com/mailgun/talon/blob/master/talon/signature/learning/featurespace.py#L15

Do you mind posting an example of how to use this file to turn emails in plaintext into the format that would allow us to train talon on our own data sets?

**Comment by obukhov-sergey** [comment]
Fixed with https://github.com/mailgun/talon/pull/177

**Comment by qxh5696** [comment]
Thanks for the update! Just to clarify, 

> "/path/to/talon/signature/data/classifier"

This is where the classifier that we are training in this example would be saved right?
