### ISSUE TITLE
Parsing of gmail forwarded messages

### ISSUE THREAD

**Issue by SokratisVidros** [mailgun/talon#18]
Forwarded email content sent from Gmail is pruned by Talon. Normally when you forward a message you need to preserve it.

A potential improvement could detect the `------Forwarded message------` text inside the first child node of the `<div class="gmail_quote">` element and output the original message if gmail_quote div is not deeply nested.

Thanks,
Sokratis

**Comment by Savageman** [comment]
Hello, we got an error when processing gmail message after this patch:

```
Traceback (most recent call last):
[...]
 File "/usr/local/lib/python2.7/dist-packages/talon/quotations.py", line 352, in extract_from_html
   cut_quotations = (html_quotations.cut_gmail_quote(html_tree) or
 File "/usr/local/lib/python2.7/dist-packages/talon/html_quotations.py", line 81, in cut_gmail_quote
   if gmail_quote and not RE_FWD.match(gmail_quote[0].text):
TypeError: expected string or buffer
```

**Comment by Savageman** [comment]
:up: @obukhov-sergey Gmail is quite popular, can you reproduce the error too?
