### ISSUE TITLE
Dutch Apple mail splitter

### ISSUE THREAD

**Issue by timhanssen** [mailgun/talon#32]
Hi all,

After a request to support, I got this link to submit a new dutch splitter format. Hope this improves this great libary!

"Op 14 jan. 2015, om 13:52 heeft ... het volgende geschreven:"
Op <:date>. om <time> heeft <author> het volgende geschreven:

How should i proceed?

**Comment by jeremyschlatter** [comment]
Hi Tim,

Take a look at https://github.com/mailgun/talon/pull/29. From a quick look I think you can extend that change to cover Dutch.

**Comment by obukhov-sergey** [comment]
Hi @timhanssen, just checked that latest version of talon already supports this format! It probably was in one of the PRs we recently merged.
