### ISSUE TITLE
Numpy dep is obsolete

### ISSUE THREAD

**Issue by jace** [mailgun/talon#51]
Talon requires Numpy 1.6.1, while the latest version is 1.9.2. Version 1.6.1 doesn't install on Mac OS X, failing with this error: `clang: error: invalid argument '-faltivec' only allowed with 'ppc/ppc64/ppc64le'`

**Comment by obukhov-sergey** [comment]
Hi @jace. Thanks for letting us know. The setup.py file has been updated to unpin numpy version.
