### ISSUE TITLE
`extract_from_html` breaks when xhtml encoding specified in document

### ISSUE THREAD

**Issue by dgouldin** [mailgun/talon#52]
To reproduce, add the following line to the top of `tests/fixtures/html_replies/hotmail.html`:

`<?xml version="1.0" encoding="UTF-8"?>`

and run `nosetests tests/html_quotations_test.py:test_hotmail_reply`. lxml cannot parse html documents from a unicode string when the encoding is declared in the document.

**Comment by obukhov-sergey** [comment]
Hi @dgouldin, thanks for reporting. lxml [documentation](http://lxml.de/parsing.html#python-unicode-strings) discourages from converting html / xml data to unicode. The parser can handle unicode but this requires that unicode strings do not specify an encoding themselves. The test has been corrected to not decode the data prior to extracting quotations.
