### ISSUE TITLE
PyML installation from SourceForge is not working

### ISSUE THREAD

**Issue by vjong** [mailgun/talon#53]
During setup of Talon there's a CDN reference that is ending in an unreachable and breaks the installation.

Also, is there any news on moving to scikit?

**Comment by tgwizard** [comment]
Hi @vjong. I've created a fork of talon, https://github.com/tictail/claw, where I've removed the references to PyML and its dependencies (which I didn't use or need). If you don't need the ML parts of talon, perhaps that could suit you as well?

**Comment by vjong** [comment]
Thanks! We'll definitely have a look at that.

**Comment by obukhov-sergey** [comment]
Hi @vjong, @tgwizard. Talon was moved to scikit. PyPi has also been updated. let us know if you run into any issues during installation, etc.
