### ISSUE TITLE
pyml failed while installting talon via pip(ubuntu)

### ISSUE THREAD

**Issue by GomesNayagam** [mailgun/talon#7]
I felt few things here:
any idea why scikit was not used rather pyml? which naturally ease the deployment.
how does multiple mail reply chain works to extract all the signature?

sh: 0: getcwd() failed: No such file or directory

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0tar: PyML-0.7.9: Cannot mkdir: No such file or directory

tar: PyML-0.7.9: Cannot mkdir: No such file or directory

tar: PyML-0.7.9/data: Cannot mkdir: No such file or directory

**Comment by ad-m** [comment]
I have this issue to. I up my log at https://gist.github.com/ad-m/00bef0b21d2d78bb74ae .

**Comment by tgwizard** [comment]
:+1: on this. PyML seems to be only on SourceForge, and now that [SourceForge is partially down](http://sourceforge.net/blog/sourceforge-infrastructure-and-service-restoration/), it is impossible to install talon:

```
Collecting PyML==0.7.9 (from -r requirements.txt (line 46))
  Could not find a version that satisfies the requirement PyML==0.7.9 (from -r requirements.txt (line 46)) (from versions: )
  No matching distribution found for PyML==0.7.9 (from -r requirements.txt (line 46))
make: *** [install] Error 1
```

**Comment by tgwizard** [comment]
Apologies, please disregard my comment above. I didn't realize that talon installed PyML on its own by curling down a tarball. That installation procedure should be indicative in itself that we should perhaps migrate away from PyML.

**Comment by obukhov-sergey** [comment]
Hi all. Talon has been migrated to scikit.
