### ISSUE TITLE
More modular distribution of ML components

### ISSUE THREAD

**Issue by amccormick-indeed** [mailgun/talon#96]
The ML features for signature extraction are neat; they make the module much much larger than it would be without them: ~200MB vs ~15MB.  Would it be possible to further modularize the package so that the ML portions could be selectively included, and excluded for those who want a smaller distribution?

**Comment by obukhov-sergey** [comment]
Hi @amccormick-indeed I like the idea but I don't plan to work on such feature in the nearest future since we use ML part in production.

**Comment by amccormick-indeed** [comment]
Thanks.  Given that you like the idea, I'll see if I can move forward on it myself and submit a patch.

**Comment by timabbott** [comment]
@umairwaheed added support for doing this in #97; it'd be great if someone could give that a review.  @amccormick-indeed if you want to help test this out, you can see how we've integrated this off of @umairwaheed's branch in https://github.com/zulip/zulip/issues/1210.
